---

- name: Create Packer AEM AWS resources stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:

    - name: Create AWS resources stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ aws.resources.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../templates/cloudformation/aws-resources.yaml"
        template_parameters:
          StackPrefix: "{{ stack_prefix }}"
          PackerAemS3Bucket: "{{ aws.resources.s3_bucket }}"
          EnableSecretsManager: "{{ aws.resources.enable_secrets_manager | bool }}"
          CreatePackerIAMRole: "{{ aws.resources.create_iam_packer_role | bool }}"
          CreatePackerBucket: "{{ aws.resources.create_s3_bucket | bool }}"
